table Actual_Costs
	isHidden
	lineageTag: 7205e073-5207-42df-a2c9-e689b7c12d2a

	column Projet_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 620b04b2-8c12-4576-ad29-1a7f27809db2
		summarizeBy: count
		sourceColumn: Projet_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Phase
		dataType: string
		isHidden
		lineageTag: 2ca695c2-3a4c-4d8f-a0ad-f023b34c9af7
		summarizeBy: none
		sourceColumn: Phase

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Actual_Cost
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6a1149dc-e1d5-4959-aec7-4d293eeed8f1
		summarizeBy: sum
		sourceColumn: Actual_Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Actual_Costs = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Morgi\Desktop\OpenClassrooms Projets\Projet 7 - Power BI\Projet 7 - Projet Sanitoral\data\sanitoral_data.xlsx")),
				    Actual_Costs_sheet = Source{[Item="Actual_Costs",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Dernières lignes supprimées" = Table.RemoveLastN(Actual_Costs_sheet, each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Premières lignes supprimées" = Table.Skip(#"Dernières lignes supprimées", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"En-têtes promus" = Table.PromoteHeaders(#"Premières lignes supprimées", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Proj_ID", Int64.Type}, {"Phase", type text}, {"Actual_Cost", Int64.Type}}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Type modifié",{{"Proj_ID", "Projet_ID"}})
				in
				    #"Colonnes renommées"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

