table Actual_Delivrables
	isHidden
	lineageTag: f6811337-94c1-416a-88c6-62a525dbd6b7

	column Project_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b649fe08-dfd0-435c-b72f-d482ec9320cf
		summarizeBy: count
		sourceColumn: Project_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Phase
		dataType: string
		isHidden
		lineageTag: b356070d-ac10-4227-9bf4-79fe53f9cae6
		summarizeBy: none
		sourceColumn: Phase

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Actual_Deliverables
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 07f3bd7c-86c9-47d0-a32b-c49999acca0e
		summarizeBy: sum
		sourceColumn: Actual_Deliverables

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Actual_Delivrables = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Morgi\Desktop\OpenClassrooms Projets\Projet 7 - Power BI\Projet 7 - Projet Sanitoral\data\sanitoral_data.xlsx")),
				    Actual_Delivrable_sheet = Source{[Item="Actual_Delivrable",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Dernières lignes supprimées" = Table.RemoveLastN(Actual_Delivrable_sheet, each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Premières lignes supprimées" = Table.Skip(#"Dernières lignes supprimées", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"En-têtes promus" = Table.PromoteHeaders(#"Premières lignes supprimées", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"ID", Int64.Type}, {"Phase", type text}, {"Actual_Deliverables", Int64.Type}}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Type modifié",{{"ID", "Project_ID"}})
				in
				    #"Colonnes renommées"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

