table Mesures
	lineageTag: acd111ce-f9ec-4bc6-ab04-6ae0a406640b

	measure 'Alert Cost' = ```
			
			COALESCE(
			    COUNTROWS(
			        FILTER(
			            Project_Phase, 
			            Project_Phase[Cost_Over_Budget_15%] = 1
			        )
			    ),
			    0
			)
			```
		formatString: 0
		displayFolder: Alert
		lineageTag: 99c6ef46-b634-409b-90f4-95e1fd889dba

	measure 'Alert Deadline' = ```
			
			COALESCE(
			    COUNTROWS(
			        FILTER(
			            Project_Phase, 
			            Project_Phase[Duration_Over_15%] = 1
			        )
			    ),
			    0
			)
			```
		formatString: 0
		displayFolder: Alert
		lineageTag: 63eaf795-4764-4257-8570-a8427529708b

	measure 'Alert Not Complete and Late' = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Project_Phase), 
			        Project_Phase[Late] = 1
			    ),
			    0
			)
			```
		formatString: 0
		displayFolder: Alert
		lineageTag: 0cb91e7a-7558-4c5e-ac86-060150e031b8

	measure 'Alert Incomplete' = ```
			
			IF(
			    ISBLANK(
			        COUNTROWS(
			            FILTER(
			                Project_Phase, 
			                Project_Phase[Deliverables_Under_15%] = 1
			            )
			        )
			    ),
			    0,
			    COUNTROWS(
			        FILTER(
			            Project_Phase, 
			            Project_Phase[Deliverables_Under_15%] = 1
			        )
			    )
			)
			```
		formatString: 0
		displayFolder: Alert
		lineageTag: c238ba4e-18bf-418a-8ea7-462e8698ad0e

	measure Complete =
			
			CALCULATE(
			    COUNTROWS(Project_Phase),
			    Project_Phase[Complete] = 1
			)
		formatString: 0
		lineageTag: b20969ef-0ae6-4acd-b9b2-ff8741f8414a

	measure Progress = DIVIDE(SUM(Project_Phase[Actual_Deliverables]), SUM(Project_Phase[Planned_Deliverables]), 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 6d287b6d-3f57-4ac4-95bb-aa9af717bf66

	measure 'AVG late' =
			DIVIDE(
			    SUM(Project_Phase[Nb_Days_Late]),
			    DISTINCTCOUNT(Project_Phase[Project_ID])
			)
		formatString: 0
		lineageTag: f4ecbe2d-70d3-4731-913d-97cc1a138048

	measure 'Max Gauge' = SUM(Project_Phase[Planned_Cost]) * 1.1
		lineageTag: aadc530a-587d-40a5-9749-1b1e10284bce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total days late' = SUM(Project_Phase[Nb_Days_Late])
		formatString: 0
		lineageTag: d2fe80fb-e95d-498b-8dac-ddea75dab1da

	measure 'Total cost overrun' = SUM(Project_Phase[Cost_overrun])
		formatString: 0
		lineageTag: 38877675-aec6-4350-8d12-3faa926cabfd

	measure 'No Alert' = ```
			
			IF(
			    SUM(Project_Phase[Cost_Over_Budget_15%]) = 0 &&
			    SUM(Project_Phase[Deliverables_Under_15%]) = 0 &&
			    SUM(Project_Phase[Duration_Over_15%]) = 0,
			    "No Alert",
			    0
			)
			
			```
		lineageTag: b19e5548-0ebf-4cd9-bbc2-c4deec5f5e53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Mesures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Colonne 1" = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Colonne 1", type text}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"Colonne 1"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

